# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ":zap: KAPOW"
url: https://blog.gerardroche.com
email: gerard@gerardroche.com
description: A blog about stuff.
github:
  username: gerardroche
stackoverflow:
  user: 934739/gerardroche
packagecontrol:
  author: gerardroche
lang: en
timezone: UTC
permalink: pretty
strict_front_matter: true
liquid:
  error_mode: strict
sass:
  style: compressed
kramdown:
  show_warnings:  true
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image:
        path: assets/zap.png
        width: 128
        height: 128
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  archive-tags:
    output: true
    permalink: /tags/:name/
