permalink: pretty
liquid:
  error_mode: strict
sass:
  style: compressed
strict_front_matter: true
lang: en_IE
timezone: UTC
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
kramdown:
  show_warnings:  true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image:
        path: assets/zap.png
        width: 128
        height: 128
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

url: https://blog.gerardroche.com
title: ":zap: KAPOW"
description: A blog about stuff.
email: gerard@gerardroche.com

github:
  username: gerardroche

stackoverflow:
  user: 934739/gerardroche

packagecontrol:
  author: gerardroche
